{{- range $topping := .Values.pizzaToppings }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ $topping }}
data:
  myvalue: "Hello!"
  drink: soda
  food: pizza 
  topping: {{ $topping }}
{{- end }}